### ISSUE TITLE
Default instance URL to Fathom CDN

### ISSUE THREAD

**Issue by alexlafroscia** [lgraubner/gatsby-plugin-fathom#1]
If you're paying for Fathom, you can (should?) use Fathom's own hosted version of the tracker script rather than the one hosted by your own instance.

I think it would make sense to default the instance URL to `cdn.usefathom.com` and document in the `REAMDE` that you can _just_ provide the tracking ID if you're using the hosted version.

If you like that idea, I'd be happy to make a PR that makes those changes!

**Comment by lgraubner** [comment]
Sounds good to me! Feel free to create a PR. Please make sure to document the difference here. Thanks!
