### ISSUE TITLE
Add ability to prevent tracking on specific domains

### ISSUE THREAD

**Issue by rileyamos** [lgraubner/gatsby-plugin-fathom#10]
**Issue:**
Currently, gatsby-plugin-fathom will log analytics while in the development environment (ie. localhost). This is not ideal as it creates noise in the overall analytics data.

**Request:**
Implement a domain blacklist which would ensure that analytics are not tracked if Fathom is triggered from a domain on the list.

A example implementation can be found in the Fathom documentation:
https://usefathom.com/support/localhost

Ideally we would be able to configure the list in the `gatsby-config.js`, like so:

```
// gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-fathom',
      options: {
        // Fathom server URL. Defaults to `cdn.usefathom.com`
        trackingUrl: 'your-fathom-instance.com',
        // Unique site id
        siteId: 'FATHOM_SITE_ID',
        // Domain Blacklist
        fathomExcludeHostnames: ['localhost']
      }
    }
  ]
}
```

**Comment by lgraubner** [comment]
Sounds useful. Feel free to provide a PR.

**Comment by libuk** [comment]
Hi all, I'm happy to take this on @lgraubner @rileyamos

**Comment by lgraubner** [comment]
@libuk Go for it! 👍
