### ISSUE TITLE
Update to latest version of tracking code

### ISSUE THREAD

**Issue by mrmadhat** [lgraubner/gatsby-plugin-fathom#17]
The current tracking code used by this plugin is not the latest tracking code and doesn't support new fathom features such as `fathom.blockTrackingForMe()`.

I would like to work on a pull request for this, I think adding an option to allow site owners to choose between the old embed code and new one is the most appropriate route. Does anyone have any opinions on this?

**Comment by lgraubner** [comment]
I appreciate every PR, go for it. :)

**Comment by mrmadhat** [comment]
Ok cool, I'l spend some time on this this weekend
