### ISSUE TITLE
Clarify deprecation notices across the places this package is advertised

### ISSUE THREAD

**Issue by motin** [lgraubner/gatsby-plugin-fathom#26]
This plugin doesn't work any longer, and its deprecation is mentioned in this Github repo's readme and on https://www.npmjs.com/package/gatsby-plugin-fathom, but it is not mentioned in either https://www.gatsbyjs.com/plugins/gatsby-plugin-fathom/ nor https://www.npmjs.com/package/gatsby-plugin-fathom-v2 (which seems like something that ought to work given https://www.npmjs.com/package/gatsby-plugin-fathom being deprecated).

What even is the -v2 npm package? All in all, this is rather confusing...

**Comment by lgraubner** [comment]
I don't know what the v2 package on NPM is, but it seems like a fork. This package is deprecated as the Fathom Docs state there is no plugin necessary (https://usefathom.com/integrations/gatsbyjs).
Some people stated there is still need for a gatsby plugin, but I had no time digging into it. PRs are welcome.

**Comment by kennethormandy** [comment]
The v2 package appears to be a published version of the v2 PR: #23

[The README from the PR](https://github.com/lgraubner/gatsby-plugin-fathom/blob/887b018ddee35cc48fb46dadd8d270222d0f8728/README.md) is [the README on npm](https://www.npmjs.com/package/gatsby-plugin-fathom-v2), but it looks like @lgraubner is still set as the author in the `package.json` 

I also think that a plugin is still preferable, but that PR already solves it: https://github.com/lgraubner/gatsby-plugin-fathom/pull/23#issuecomment-757357473

**Comment by lgraubner** [comment]
This package is under active development and will be officially supported by Fathom. The deprecation warning was removed and v2 is published.
